#ifndef _TINYVISOR_MTRRS_H
#define _TINYVISOR_MTRRS_H

#include <Uefi.h>

#define IA32_MTRR_FIX_COUNT ((1 + 2 + 8) * 8)
#define IA32_MTRR_VARIABLE_COUNT 0xff
#define IA32_MTRR_COUNT (IA32_MTRR_FIX_COUNT + IA32_MTRR_VARIABLE_COUNT)

#define MEMORY_TYPE_UNCACHEABLE 0
#define MEMORY_TYPE_WRITE_COMBINING 1
#define MEMORY_TYPE_WRITE_THROUGH 4
#define MEMORY_TYPE_WRITE_PROTECTED 5
#define MEMORY_TYPE_WRITE_BACK 6
#define MEMORY_TYPE_INVALID 255

typedef UINT32 IA32_MEMORY_TYPE;

VOID InitializeMtrrInfo();

#endif
